apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: monitoring
  labels:
    k8s-app: argocd
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: argocd-metrics
  endpoints:
  - port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - argocd